import WithSubnavigation from '@/components/nav/nav'
import LargeWithLogoLeft from '@/components/footer'
import CallToActionWithAnnotation from '@/components/body'
import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main> 
          <WithSubnavigation/>
          <CallToActionWithAnnotation/>
          <LargeWithLogoLeft/>
      </main>
    </>
  )
}
